// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbdKolos2B.Database;

#nullable disable

namespace apbdKolos2B.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250616192119_AddedSeed")]
    partial class AddedSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbdKolos2B.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConcertId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ConcertId = 1,
                            AvailableTickets = 20,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pielgrzymka"
                        },
                        new
                        {
                            ConcertId = 2,
                            AvailableTickets = 100,
                            Date = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Juwenalia"
                        },
                        new
                        {
                            ConcertId = 3,
                            AvailableTickets = 300,
                            Date = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urysnalia"
                        });
                });

            modelBuilder.Entity("apbdKolos2B.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Jane",
                            LastName = "Kowalski",
                            PhoneNumber = "999-999-999"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Krzysztof",
                            LastName = "Zalewski",
                            PhoneNumber = "777-777-777"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Grzegorz",
                            LastName = "Floryda"
                        });
                });

            modelBuilder.Entity("apbdKolos2B.Models.PurchasedTicket", b =>
                {
                    b.Property<int>("TicketConcertId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketConcertId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchasedTickets");

                    b.HasData(
                        new
                        {
                            TicketConcertId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 1,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 2,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 2,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 3,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 3,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("apbdKolos2B.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            SeatNumber = 200,
                            SerialNumber = "PDW1111"
                        },
                        new
                        {
                            TicketId = 2,
                            SeatNumber = 15,
                            SerialNumber = "PDW2222"
                        },
                        new
                        {
                            TicketId = 3,
                            SeatNumber = 20,
                            SerialNumber = "PDW3333"
                        });
                });

            modelBuilder.Entity("apbdKolos2B.Models.TicketConcert", b =>
                {
                    b.Property<int>("TicketConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketConcertId"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("TicketConcertId");

                    b.HasIndex("ConcertId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketConcerts");

                    b.HasData(
                        new
                        {
                            TicketConcertId = 1,
                            ConcertId = 1,
                            Price = 15.99,
                            TicketId = 1
                        },
                        new
                        {
                            TicketConcertId = 2,
                            ConcertId = 2,
                            Price = 20.989999999999998,
                            TicketId = 1
                        },
                        new
                        {
                            TicketConcertId = 3,
                            ConcertId = 3,
                            Price = 27.870000000000001,
                            TicketId = 2
                        },
                        new
                        {
                            TicketConcertId = 4,
                            ConcertId = 1,
                            Price = 123.45,
                            TicketId = 3
                        },
                        new
                        {
                            TicketConcertId = 5,
                            ConcertId = 2,
                            Price = 112.98999999999999,
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("apbdKolos2B.Models.PurchasedTicket", b =>
                {
                    b.HasOne("apbdKolos2B.Models.Customer", "Customer")
                        .WithMany("PurchasedTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolos2B.Models.TicketConcert", "TicketConcert")
                        .WithMany("PurchasedTickets")
                        .HasForeignKey("TicketConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TicketConcert");
                });

            modelBuilder.Entity("apbdKolos2B.Models.TicketConcert", b =>
                {
                    b.HasOne("apbdKolos2B.Models.Concert", "Concert")
                        .WithMany("TicketConcerts")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolos2B.Models.Ticket", "Ticket")
                        .WithMany("TicketConcerts")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("apbdKolos2B.Models.Concert", b =>
                {
                    b.Navigation("TicketConcerts");
                });

            modelBuilder.Entity("apbdKolos2B.Models.Customer", b =>
                {
                    b.Navigation("PurchasedTickets");
                });

            modelBuilder.Entity("apbdKolos2B.Models.Ticket", b =>
                {
                    b.Navigation("TicketConcerts");
                });

            modelBuilder.Entity("apbdKolos2B.Models.TicketConcert", b =>
                {
                    b.Navigation("PurchasedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
