// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbdKolos2ProbnyTest.Database;

#nullable disable

namespace apbdKolos2ProbnyTest.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250616234737_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Backpack", b =>
                {
                    b.Property<int>("CharacterdId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CharacterdId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Backpacks");

                    b.HasData(
                        new
                        {
                            CharacterdId = 1,
                            ItemId = 1,
                            Amount = 3
                        },
                        new
                        {
                            CharacterdId = 1,
                            ItemId = 2,
                            Amount = 1
                        },
                        new
                        {
                            CharacterdId = 1,
                            ItemId = 3,
                            Amount = 2
                        },
                        new
                        {
                            CharacterdId = 2,
                            ItemId = 1,
                            Amount = 2
                        },
                        new
                        {
                            CharacterdId = 2,
                            ItemId = 3,
                            Amount = 1
                        },
                        new
                        {
                            CharacterdId = 3,
                            ItemId = 1,
                            Amount = 8
                        },
                        new
                        {
                            CharacterdId = 3,
                            ItemId = 3,
                            Amount = 6
                        });
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CurrentWeight = 60,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            MaxWeight = 80
                        },
                        new
                        {
                            CharacterId = 2,
                            CurrentWeight = 50,
                            FirstName = "Krzysztof",
                            LastName = "Zalewski",
                            MaxWeight = 65
                        },
                        new
                        {
                            CharacterId = 3,
                            CurrentWeight = 65,
                            FirstName = "Jakub",
                            LastName = "Cash",
                            MaxWeight = 92
                        });
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.CharacterTitle", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId", "TitileId");

                    b.HasIndex("TitileId");

                    b.ToTable("CharacterTitles");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitileId = 1,
                            AcquiredAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 1,
                            TitileId = 2,
                            AcquiredAt = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitileId = 3,
                            AcquiredAt = new DateTime(2021, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitileId = 2,
                            AcquiredAt = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitileId = 3,
                            AcquiredAt = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Name = "Puszka",
                            Weight = 3
                        },
                        new
                        {
                            ItemId = 2,
                            Name = "Latarka",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 3,
                            Name = "Zapalniczka",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Title", b =>
                {
                    b.Property<int>("TitileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitileId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TitileId");

                    b.ToTable("Titiles");

                    b.HasData(
                        new
                        {
                            TitileId = 1,
                            Name = "Technik"
                        },
                        new
                        {
                            TitileId = 2,
                            Name = "Inzynier"
                        },
                        new
                        {
                            TitileId = 3,
                            Name = "Kucharz"
                        });
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Backpack", b =>
                {
                    b.HasOne("apbdKolos2ProbnyTest.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolos2ProbnyTest.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.CharacterTitle", b =>
                {
                    b.HasOne("apbdKolos2ProbnyTest.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolos2ProbnyTest.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("apbdKolos2ProbnyTest.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
