// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Probny2025ZRozwiazaniem.Data;

#nullable disable

namespace Probny2025ZRozwiazaniem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250615142515_AddedOrder")]
    partial class AddedOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Probny2025ZRozwiazaniem.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            ClientId = 2,
                            FirstName = "Michal",
                            LastName = "Wisniewski"
                        },
                        new
                        {
                            ClientId = 3,
                            FirstName = "Krzysztof",
                            LastName = "Blachowicz"
                        });
                });

            modelBuilder.Entity("Probny2025ZRozwiazaniem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "CD",
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Zmywarka",
                            Price = 200.2m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Wanna",
                            Price = 50.3m
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Prysznic",
                            Price = 35.89m
                        });
                });

            modelBuilder.Entity("Probny2025ZRozwiazaniem.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Zlozony"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "W trakcie"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Wykonany"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
