// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbdKolo2A.Database;

#nullable disable

namespace apbdKolo2A.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250616142100_AddedSeedsAndPrecisionOnPrice")]
    partial class AddedSeedsAndPrecisionOnPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbdKolo2A.Models.AvailableProgram", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailableProgramId"));

                    b.Property<double>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WashingMachineId");

                    b.ToTable("AvailablePrograms");

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            Price = 10.99,
                            ProgramId = 1,
                            WashingMachineId = 1
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            Price = 12.5,
                            ProgramId = 2,
                            WashingMachineId = 1
                        },
                        new
                        {
                            AvailableProgramId = 3,
                            Price = 14.0,
                            ProgramId = 2,
                            WashingMachineId = 2
                        },
                        new
                        {
                            AvailableProgramId = 4,
                            Price = 11.6,
                            ProgramId = 3,
                            WashingMachineId = 2
                        },
                        new
                        {
                            AvailableProgramId = 5,
                            Price = 20.0,
                            ProgramId = 1,
                            WashingMachineId = 3
                        },
                        new
                        {
                            AvailableProgramId = 6,
                            Price = 6.5999999999999996,
                            ProgramId = 3,
                            WashingMachineId = 3
                        });
                });

            modelBuilder.Entity("apbdKolo2A.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = "111-222-333"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Krzysztof",
                            LastName = "Zalewski",
                            PhoneNumber = "333-444-555"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Aleksander",
                            LastName = "Ciesla",
                            PhoneNumber = "666-777-888"
                        });
                });

            modelBuilder.Entity("apbdKolo2A.Models.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            DurationMinutes = 20,
                            Name = "Szybkie",
                            TemperatureCelsius = 50
                        },
                        new
                        {
                            ProgramId = 2,
                            DurationMinutes = 120,
                            Name = "Delikatne",
                            TemperatureCelsius = 30
                        },
                        new
                        {
                            ProgramId = 3,
                            DurationMinutes = 60,
                            Name = "Sportowe",
                            TemperatureCelsius = 40
                        });
                });

            modelBuilder.Entity("apbdKolo2A.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseHistories");

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2
                        },
                        new
                        {
                            AvailableProgramId = 3,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2022, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 6
                        });
                });

            modelBuilder.Entity("apbdKolo2A.Models.WashingMachine", b =>
                {
                    b.Property<int>("WashingMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WashingMachineId"));

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WashingMachineId");

                    b.ToTable("WashingMachines");

                    b.HasData(
                        new
                        {
                            WashingMachineId = 1,
                            MaxWeight = 20.0,
                            SerialNumber = "PDW123456"
                        },
                        new
                        {
                            WashingMachineId = 2,
                            MaxWeight = 12.0,
                            SerialNumber = "PDW987654"
                        },
                        new
                        {
                            WashingMachineId = 3,
                            MaxWeight = 5.5,
                            SerialNumber = "PDW673028"
                        });
                });

            modelBuilder.Entity("apbdKolo2A.Models.AvailableProgram", b =>
                {
                    b.HasOne("apbdKolo2A.Models.Program", "Program")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolo2A.Models.WashingMachine", "WashingMachine")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("WashingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("WashingMachine");
                });

            modelBuilder.Entity("apbdKolo2A.Models.PurchaseHistory", b =>
                {
                    b.HasOne("apbdKolo2A.Models.AvailableProgram", "AvailableProgram")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("AvailableProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbdKolo2A.Models.Customer", "Customer")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailableProgram");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("apbdKolo2A.Models.AvailableProgram", b =>
                {
                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("apbdKolo2A.Models.Customer", b =>
                {
                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("apbdKolo2A.Models.Program", b =>
                {
                    b.Navigation("AvailablePrograms");
                });

            modelBuilder.Entity("apbdKolo2A.Models.WashingMachine", b =>
                {
                    b.Navigation("AvailablePrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
